environment:
  language: java
  language_versions: 1.7.0_80
  packages:
    - apache_maven-3.2.3

build:
  run:
    - mvn install
  <% if ( GIT_URL =~ /groupon\/DotCiInstallPackages/ ) %>
    <% if ( DOTCI_TAG =~ /DotCiInstallPackages-[0-9]+\.[0-9]+\.[0-9]+.*/ ) { %>
    - mvn -DskipTests=true release:perform
    <% } %>
    - mvn -DskipTests=true deploy
  <% } %>

plugins:
  - artifacts: 'target/DotCiInstallPackages.*'
