environment:
  language: java
  language_versions: 1.7.0_80
  packages:
    - apache_maven-3.2.3

build:
  run:
    - mvn install
  <% if ( GIT_URL =~ /DotCi\/DotCi-InstallPackages/ ) %>
    <% if ( DOTCI_TAG =~ /DotCi-InstallPackages-[0-9]+\.[0-9]+\.[0-9]+.*/ ) { %>
    - mvn -Darguments="-DskipTests=true" release:perform
    <% } %>
    - mvn -DskipTests=true deploy
  <% } %>

plugins:
  - artifacts: 'target/DotCi-InstallPackages.*'
